SELECT A.FUNCTION, B.SCHEDULER_NAME, B.NEXT_RUN_DTTM, (CASE WHEN B.NEXT_RUN_DTTM >= SYSDATE THEN 'GOOD' ELSE 'BAD' END) IS_OK FROM 
(
SELECT 'DUG DO Create' FUNCTION FROM OM_SCHED_EVENT
UNION SELECT 'DUG Order Seq Number By Store' FUNCTION FROM OM_SCHED_EVENT
UNION SELECT 'Manh Order Push Scheduler' FUNCTION FROM OM_SCHED_EVENT
UNION SELECT 'Mapping Clone to Master' FUNCTION FROM OM_SCHED_EVENT
UNION SELECT 'RP to EOM DO Create' FUNCTION FROM OM_SCHED_EVENT
) A
LEFT OUTER JOIN
(
SELECT 'DUG DO Create' FUNCTION, 'DUG DO Create' SCHEDULER_NAME, MAX(SCHEDULED_DTTM) NEXT_RUN_DTTM FROM OM_SCHED_EVENT WHERE EVENT_OBJECTS LIKE '%DUG DO Create%'
UNION SELECT 'DUG Order Seq Number By Store' FUNCTION, 'SFWYSequencingDUGOrderPOScheduler' SCHEDULER_NAME, MAX(SCHEDULED_DTTM) NEXT_RUN_DTTM  FROM OM_SCHED_EVENT WHERE EVENT_OBJECTS LIKE '%SFWYSequencingDUGOrderPOScheduler%' 
UNION SELECT 'Mapping Clone to Master' FUNCTION, 'SFWYSectionTableDataCloneScheduler' SCHEDULER_NAME, MAX(SCHEDULED_DTTM) NEXT_RUN_DTTM FROM OM_SCHED_EVENT WHERE EVENT_OBJECTS LIKE '%SFWYSectionTableDataCloneScheduler%' 
UNION SELECT 'RP to EOM DO Create' FUNCTION, 'Create DO WR' SCHEDULER_NAME, MAX(SCHEDULED_DTTM) NEXT_RUN_DTTM FROM OM_SCHED_EVENT WHERE EVENT_OBJECTS LIKE '%Create DO WR%'
UNION SELECT 'Manh Order Push Scheduler' FUNCTION, 'SFWYShipOrderScheduler' SCHEDULER_NAME, MAX(SCHEDULED_DTTM) NEXT_RUN_DTTM FROM OM_SCHED_EVENT WHERE EVENT_OBJECTS LIKE '%SFWYShipOrderScheduler%'
) B
ON A.FUNCTION=B.FUNCTION
ORDER BY A.FUNCTION;